### ISSUE TITLE
Create data model schema of study management

### ISSUE THREAD

**Issue by nivemaham** [RADAR-CNS/ManagementPortal#1]
Create the basic entities and relationships to manage a pilot study

**Comment by dennyverbeeck** [comment]
WIP here: https://docs.google.com/drawings/d/1flILWgpnun12nMaPiJc0V73kJMhOmA70lRZefqnBk5E/

**Comment by nivemaham** [comment]
Revised schema based on security documentations. https://docs.google.com/drawings/d/1CqSPZcImbxYfxSpWWkxzxpxbPFrWzM6CmB_pZ_F6F68/edit

**Comment by nivemaham** [comment]
Schema looks satisfactory for current mile-stone, thus closing it.
