### ISSUE TITLE
Cannot login with new users created

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-CNS/ManagementPortal#112]
Cannot login using the users created through the management portal user management page and email activation link.
Also cannot login using users created by requests to the users API.

**Comment by yatharthranjan** [comment]
The first issue above somehow mysteriously solved itself. However, we should make a note that something like this happened for future reference.
The second point about creating users through the API is possible but they will still need to reset the password using the activation link. It is not allowed to set the password through the API

**Comment by dennyverbeeck** [comment]
Ok, the issue is that the endpoint where the POST to reset the password is going to is not being ignored by the JWT security filter. I will look into it!

**Comment by yatharthranjan** [comment]
Okay so now we know the reason and its not random. What a relief. Thanks @dennyverbeeck 
A followup question - So why does the same link work for me and not for her?

**Comment by nivemaham** [comment]
I am not sure whether that would really solve this issue. We shouldn't be getting `401` for all the other request above. @dennyverbeeck any comments on that? @yatharthranjan , are you sure that the token didn't expire when you were trying this? I would assume yes, you are.

**Comment by yatharthranjan** [comment]
@nivemaham yes we just tried within 5 mins of generating the link

**Comment by afolarin** [comment]
There is no local state that should determine if the authentication should work -- this is the puzzling bit.
Incidentally when we previously went from not working to working the only steps I took were to try this through my hotspot network using an incognito window, it worked first time after not working several times. Interestingly also once it worked for me it then worked for @yatharthranjan :confused:

**Comment by nivemaham** [comment]
My guess is it has to do with the tokens, browser storage. Will do some investigation.

**Comment by dennyverbeeck** [comment]
The link worked for @yatharthranjan probably because he was still logged in himself. But if you're not logged in the `JwtAuthenticationFilter` denies access on the endpoints it's configured for. Currently it's configured on `/api/*` and `/management/*`. It should ignore requests to `/api/account/reset_password/*`, since on those endpoints we expect a non-authenticated user. I'm pushing a fix in a few minutes.

**Comment by yatharthranjan** [comment]
Yes I can confirm this that when I logout from admin, and then use the activation link, I am also not able to reset the password. So I guess this should solve it.
