### ISSUE TITLE
All updates made in the MP disappear when stopped

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-CNS/ManagementPortal#113]
When the Management Portal app container is stopped and removed and then started again, All the changes that were made are gone. Its like it was just instantiated with only the demo entities present.
When I look in the postgres data directory, it shows that its empty. 
Could it be that postgres data is still being saved inside the container and not on the mounted volume?

**Comment by nivemaham** [comment]
What was your setup? Was it in prod profile. I never had this issue.

**Comment by afolarin** [comment]
looks like the postgres container db volume is updating. Can you check the entities are still in the db?
```
root@bc916b6f1c1d:/# ls -l /var/lib/postgresql/data/base
total 24
drwx------ 2 postgres postgres  4096 Nov  1 12:22 1
drwx------ 2 postgres postgres  4096 Nov  1 12:22 12406
drwx------ 2 postgres postgres  4096 Nov  1 12:23 12407
drwx------ 2 postgres postgres 12288 Nov  1 15:56 1638sudo ls -l 

/var/lib/docker/volumes/48ffca67772eb53ecb46e8791da225e24dd4c150c011b81022a5b9921f0db7bc/_data/base
total 24
drwx------ 2 999 docker  4096 Nov  1 12:22 1
drwx------ 2 999 docker  4096 Nov  1 12:22 12406
drwx------ 2 999 docker  4096 Nov  1 12:23 12407
drwx------ 2 999 docker 12288 Nov  1 15:56 16384
```

**Comment by yatharthranjan** [comment]
Mounting the data directory did the trick.
```
    volumes:
      - "${MP_POSTGRES_DIR}/data/:/var/lib/postgresql/data/"
```

**Comment by yatharthranjan** [comment]
Solved with https://github.com/RADAR-CNS/RADAR-Docker/pull/57
