### ISSUE TITLE
Token storage and CSRF protection

### ISSUE THREAD

**Issue by dennyverbeeck** [RADAR-CNS/ManagementPortal#117]
@nivemaham did research into this and found these articles: [Should we refresh token](https://github.com/jhipster/generator-jhipster/issues/441), [session storage or localstorage to store token](https://github.com/jhipster/generator-jhipster/issues/3405 ) and [an approach took by jhipster to solve it by using server-side sessions](https://github.com/jhipster/generator-jhipster/issues/5752).

We are storing our JWT in web storage which makes it vulnerable to XSS attacks. Recommendation is to store it as an http-only cookie. We also don't have CSRF protection on our api endpoints, we do have it on the OAuth endpoints though.

**Comment by nivemaham** [comment]
I am working on something similar for other issues. Will push soon
