### ISSUE TITLE
Device type creation: Dynamic source registration

### ISSUE THREAD

**Issue by dennyverbeeck** [RADAR-CNS/ManagementPortal#125]
Can not set the dynamic source registration when creating a new device type, either when creating or editing. There should be a checkbox to enable or disable dynamic source registration.

**Comment by dennyverbeeck** [comment]
Correction: clicking the label 'Dynamic source registration' and then saving actually toggles the state, so there might be display issue.

**Comment by nivemaham** [comment]
@dennyverbeeck i tested this on latest dev and i do not see any problems. Clicking on the Dynamic source registration checkbox should change the state, so should be the display.
