### ISSUE TITLE
Throwing exceptions doesn't show the alert message on the front end.

### ISSUE THREAD

**Issue by nivemaham** [RADAR-CNS/ManagementPortal#137]
We need to find a unique way of addressing exceptions from back-end to clients. Throwing custom exceptions give well formatted HTTP response, however it does not show the alert message in front-end app. We are using bad-request with HTTP headers and custom-exceptions in various places. We should find one solution that would work for all and stick to that in all cases.

**Comment by dennyverbeeck** [comment]
I think the custom exception approach would be best. This way we can use the `ExceptionTranslator` to manage adding the necessary headers in one place instead of duplicating the code for adding the headers over and over again in the various resource classes.
