### ISSUE TITLE
Create unique patient id generator and prepersist when a patient is being created

### ISSUE THREAD

**Issue by nivemaham** [RADAR-CNS/ManagementPortal#15]
We need to have a mechanism to have user-friendly, still anonymous and unique id to be used as the user-name/login of a patient. This is should be generated by the back-end and per-persisted. Once a patient is being created it should be saved as the user.login. 
This would allow us to have server-side validations of the unique id before the patient is being created

**Comment by nivemaham** [comment]
@fnobilia and @blootsvoets Any particular suggestions about this?

**Comment by dennyverbeeck** [comment]
It will depend also on where this will be used. If it is only to allow the active and passive apps to authenticate, they could make use of a magic link type of setup, like @fnobilia  suggested. This would give the apps a token and they can renew the token as necessary.
As for generating human-readable names we could do something as simple as <project-name>-<random-4-digit-number>.

**Comment by nivemaham** [comment]
A UUID is assigned to a `subject-login` during creation in DTO.
