### ISSUE TITLE
Implement one to one mapping between project owner and a project

### ISSUE THREAD

**Issue by nivemaham** [RADAR-CNS/ManagementPortal#16]
We want to allow only one PROJECT_ADMIN for a project.

**Comment by blootsvoets** [comment]
Why? Having multiple `PROJECT_ADMIN`s will avoid password-sharing.

**Comment by nivemaham** [comment]
If that is what we need, we could proceed with current implementation.

**Comment by nivemaham** [comment]
Decided not to implement this feature for now.
