### ISSUE TITLE
Allow dynamic oauth2 client registration with variable grant-types

### ISSUE THREAD

**Issue by nivemaham** [RADAR-CNS/ManagementPortal#18]
Currently, we support only one oauth2 client in the system. According to current situation, clients who wants to request tokens should share the client-id and client-secret internally. This is acceptable for trusted clients. This should be extended to allow multiple Oauth2 client registration like other identity provides, with custom client-id, client-secret, and scope. 
This should be discussed in detail.

**Comment by blootsvoets** [comment]
For the android and javascript application, the OAuth 2.0 Code Grant workflow could be used. This is supported by default by Spring Security OAuth. It avoids storing a client secret in an insecure location (apk or javascript file).

**Comment by dennyverbeeck** [comment]
Yes this seems appropriate. [This article](https://developers.google.com/identity/protocols/OAuth2InstalledApp) describes how to let an Android app be targeted by the `redirect_uri` that needs to be supplied with this flow, so it can capture the authorization code. However we still need to supply a `client_id`, so if we want to support 3rd party developers, dynamic registration is still needed. We won't need it for now, so i suggest moving this back out of prioritized backlog.
