### ISSUE TITLE
OAuth2Client http client

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-CNS/ManagementPortal#185]
Currently `org.radarcns.oauth.OAuth2Client` takes a static singleton HTTP client. The access to this client is not synchronised. It would be preferable to give each instance its own HTTP client. The caller can then share a connection pool, etc. If needed you can still share values like the connection pool or authenticator, if that sharing happens in a synchronised way or is easy to synchronise for external clients. For example, a `public static synchronized` method that creates singleton http client for easy use in the OAuth2Client or as a default.

**Comment by nivemaham** [comment]
I am a little confused with having `public static synchronized` to create a singleton http-client and `"It would be preferable to give each instance its own HTTP client."`. Is it singleton or instance specific http-client? @blootsvoets . Correct me if i am wrong.

**Comment by blootsvoets** [comment]
It’s an either/or: synchronized access to the singleton, or make it a normal object property and possibly pass it in the constructor (or builder). The latter seems preferable.

In addition, you could use a singleton pattern to hold the default client with weak reference if none other is provided, in that case, access to that Singleton should still be synchronized. But it seems entirely optional to do this.

**Comment by dennyverbeeck** [comment]
OkHttpClient is designed to be concurrently accessed, and the [Javadoc](https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.html) states the preferred use is to have only one instance.

> OkHttp performs best when you create a single OkHttpClient instance and reuse it for all of your HTTP calls. This is because each client holds its own connection pool and thread pools. Reusing connections and threads reduces latency and saves memory. Conversely, creating a client for each request wastes resources on idle pools.

OkHttpClient has its own locks to guard against simultaneous access, see also the [Concurrency](https://github.com/square/okhttp/wiki/Concurrency) chapter on their wiki. Therefore i don't think we should additionally synchronize access in our own code.

Should we revert this change? Or am i missing a reason to have multiple OkHttpClients? @blootsvoets  @nivemaham

**Comment by nivemaham** [comment]
For my understanding i think, the `oauth-client-util` is a utility that is being used by another component that actually requests token etc. It can be used by multiple components, but those components would want to have control over the Http-client. Given rest-api as a user of `oauth-client-util` i think letting rest-api create yet manage a single OkHttpClient with the control of its managed-pool etc would be a better choice.

**Comment by dennyverbeeck** [comment]
Ok, yes that makes a lot of sense to me. Thanks for the clarification!
