### ISSUE TITLE
Use explicit security exceptions

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-CNS/ManagementPortal#190]
Radar-auth authentication throw exceptions that extend from `RuntimeException`. This means there is no warning when they are not explicitly caught, and they can't be caught as one general exception. I'd propose to change the base class to [`GeneralSecurityException`](https://docs.oracle.com/javase/7/docs/api/java/security/GeneralSecurityException.html). Then they need to be caught explicitly, and they have a superclass that can be caught. @nivemaham @dennyverbeeck any thoughts?

**Comment by dennyverbeeck** [comment]
Indeed, makes a lot of sense to me as well!
