### ISSUE TITLE
Implement device registration for a project

### ISSUE THREAD

**Issue by nivemaham** [RADAR-CNS/ManagementPortal#20]
We want to allow device registration for a project by PROJECT_ADMIN.
These devices can later be assigned to Patients assigned to specific project.

**Comment by nivemaham** [comment]
What should be the ideal way of registering a device to the system?
1. Can a `SYS_ADMIN/PROJECT_ADMIN` register a device without-assigning it to a project?
2. If yes, do we want to list all devices to be visible to the PROJECT_ADMIN, so he can assign them to his project?
3. If no, should we validate the deviceType of the device is a valid deviceType of the corresponding project?

This will make the overall work-flow of device registration as
1. Create a project.
2. Create project's device catalog. (i.e.)
- 2.1. Create sensor data
- 2.2. Create deviceType and assign sensor data
- 2.3. Assign particular deviceType to a/his project.
3. Device registration
- 3.1. Create devices of deviceTypes assigned a project
4. Device assignment 
- 4.1. Assign devices of a project to patients of a project.

**Comment by blootsvoets** [comment]
In addition, probably a user should be able to register its own devices, if that is allowed in the project assignment. That is:
- project has a devicetype and set of sensors assigned. This assignment is marked as "has dynamic source ID".
- patient application looks up supported device type and registers its source ID with the ManagementPortal.

This is useful for the Passive Android App, which dynamically creates a source ID. This way, the source ID is still known by us, but the app will tell us what ID it will use.

**Comment by nivemaham** [comment]
I agree. I assume a rest-resource is sufficient to do this, or should we also provide user-interfaces from managementPortal side. We could further extend the deviceType model to have the "hasDynamicSource" flag and this feature could be easily realized for back-end.

**Comment by nivemaham** [comment]
Fixed here [60897a](https://github.com/RADAR-CNS/ManagementPortal/commit/60897ab12e16ace0b718f6450708855eaf992755). Flow issue#31 for dynamic source registration
