### ISSUE TITLE
Enhance the JWT token with patient, device data when necessary

### ISSUE THREAD

**Issue by nivemaham** [RADAR-CNS/ManagementPortal#26]
To validate the data transmission at RADAR-Gateway, we need to provide enough additional information with the JWT token.
E.g. Set of assigned device ids, patient-login( user-id)

**Comment by blootsvoets** [comment]
Having a set of device/source IDs in the token would very much simplify the workflow in the Gateway.

**Comment by nivemaham** [comment]
The jwt token has been enhanced with authorities of the user and devicePhysicalIds (sourceids) when the user is registered as a participant.

**Comment by blootsvoets** [comment]
Note that a source ID is not always physical and not always a device. Android source ID is self-generated; a questionnaire will also have a source ID.

**Comment by nivemaham** [comment]
@blootsvoets I agree. It is just a naming convention issue. I will rename the entities and properties.
What i meant by devicePhysicalId is indeed the unique identifier of the device.

**Comment by nivemaham** [comment]
Fixed with commit [15cc2af](https://github.com/RADAR-CNS/ManagementPortal/commit/15cc2af6949ce01dc599a781ea509ad0a46bc1b1 )
