### ISSUE TITLE
API synchrozation between Radar-Dashboard

### ISSUE THREAD

**Issue by nivemaham** [RADAR-CNS/ManagementPortal#28]
We need to discuss and decide what data are expected from Dashboard component from MP.
Accordingly, REST end-points should be implemented and/or adapted .
1. What data do we need?
2. Which format?
3. Who (The role of the user) can access an end-point?

This integration should be validated with Dashboard.

**Comment by dennyverbeeck** [comment]
Closing this since all access from components outside of the backend will go through [REST-Api](https://github.com/RADAR-CNS/RADAR-RestApi).
