### ISSUE TITLE
Support for SSO and OAuth2.0

### ISSUE THREAD

**Issue by dennyverbeeck** [RADAR-CNS/ManagementPortal#4]
Our service needs to provide endpoints for single sign-on login and OAuth2 token generation and validation.

**Comment by dennyverbeeck** [comment]
With the addition of JWT tokens for OAuth2 and opening the `check_token` and `token_key` endpoints. I suggest this can be closed.

**Comment by nivemaham** [comment]
@dennyverbeeck Where do i see the above end-points? How does this resolve single-sign-on?

**Comment by dennyverbeeck** [comment]
Sorry forgot to reference #24. The process for enabling them is described in the spring security oauth2 docs: http://projects.spring.io/spring-security-oauth/docs/oauth2.html. And it resolves SSO since any app now can check the validity of a user-supplied token. The app can check it by validating the signature, but can also check it via the check_token endpoint, which would give it a chance to check if the token was revoked ahead of it's expiry time. The endpoints are still protected by HTTP Basic authentication, where a client supplies its `client_id` and `client_secret`.

You can check the endpoints with curl:

```
$ curl localhost:8080/oauth/token_key -u ManagementPortalapp:my-secret-token-to-change-in-production
{
  "alg" : "HMACSHA256",
  "value" : "123"
}

$ curl localhost:8080/oauth/check_token -u ManagementPortalapp:my-secret-token-to-change-in-production -d "token=$token"   {
  "aud" : [ "res_ManagementPortal" ],
  "devices" : [ "a" ],
  "user_name" : "admin",
  "scope" : [ "read", "write" ],
  "exp" : 1497007251,
  "authorities" : [ "ROLE_SYS_ADMIN", "ROLE_USER" ],
  "jti" : "9551f640-9cc5-4a3f-9760-48cf9099df82",
  "client_id" : "ManagementPortalapp"
}
```
