### ISSUE TITLE
API for querying participant device assignments 

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-CNS/ManagementPortal#40]
Request for comments from @fnobilia, @nivemaham, @dennyverbeeck.

In the pRMT app, the user ID and assigned source IDs can be figured out from the JWT. The app needs a few calls to consolidate its device assignment:

1. what device types are assigned in the project where a user is participant
2. what device types the devices that are already assigned have. The device types should at least include the Android sensor provider (plugin) that should be used to read from the device, and possibly also frequencies and custom properties (like battery-dependent frequencies or activity-dependent frequencies).
3. register source IDs for devices that are not yet registered.

The first two pieces of information could be provided in a single request:
```
HTTP GET /api/user/devices
```
Response:
```json
HTTP 200
{
  "devices": [
    {
      "id": "some-uuid",
      "expectedName": "A00017",
      "expectedSourceId": "null",
      "deviceType": {
        "id": "my-uuid",
        "name": "EmpaticaE4",
        "topics": {
          "android_empatica_e4_acceleration": {
            "key_schema": "org.radarcns.key.MeasurementKey",
            "value_schema": "org.radarcns.empatica.EmpaticaE4Acceleration",
            "provider": "org.radarcns.empatica.EmpaticaE4Provider",
            "enabled": true
          }
        }
      }
    },
    {
      "id": "some-uuid2",
      "sourceId": "abcd-ewaefafa-agagagbawe-asdfas",
      "deviceType": {
        "id": "my-uuid2",
        "name": "AndroidPhone",
        "topics": {
          "android_phone_acceleration": {
            "key_schema": "org.radarcns.key.MeasurementKey",
            "value_schema": "org.radarcns.phone.PhoneAcceleration",
            "frequency": 16,
            "provider": "org.radarcns.phone.PhoneSensorProvider",
            "enabled": true
          },
          "android_phone_light": {
            "key_schema": "org.radarcns.key.MeasurementKey",
            "value_schema": "org.radarcns.phone.PhoneLight",
            "frequency": 16,
            "provider": "org.radarcns.phone.PhoneSensorProvider",
            "enabled": false
          },
          "android_phone_call": {
            "key_schema": "org.radarcns.key.MeasurementKey",
            "value_schema": "org.radarcns.phone.PhoneCall",
            "send_interval": 43200,
            "provider": "org.radarcns.empatica.PhoneCallProvider",
            "enabled": true
          }
        }
      }
    }
  ]
}
```

If a `dynamic` device type was registered and assigned to a project, when this request hits, probably an empty device with that device type should be created. If `device.expectedName` and `device.expectedSourceId` are `null`, then any device ID might be registered. The reasoning is, that a clinician may not know the technical source ID, but only the name of a device (e.g. "Empatica E4 - A00017". In another case, the source ID is autogenerated by the plugin (e.g. phone sensors) so the clinician cannot know the source ID in advance.

New devices could be registered as follows:

```json
HTTP POST /api/user/devices
{
  "devices": [
    {
      "id": "some-uuid",
      "name": "Empatica E4 - A00017",
      "sourceId": "AB:01:CD:23:EF:45",
      "firmware": "E4-2.1.0",
      "model": "E4.A",
      "os": null
    }
  ]
}
```
Response:
```
HTTP 204
```
or for an illegal request,
```json
HTTP 400
{
   "message": "Name or ID does not match acceptedIds."
}
```

The request uses the same UUIDs as provided in the previous response, and it registers a fixed `sourceId`, plus possibly some optional metadata. The backend should check that either the name or the MAC-address should match what was in `acceptableIds`. 

After registration of all source IDs, the app should request a new JWT, which will include those source IDs.

**Comment by blootsvoets** [comment]
Addendum: once a `sourceId` is registered, it should probably never change.

**Comment by fnobilia** [comment]
I am not sure if we can expose a function to create sources. A possible attacker may create fake sources. How do we distinguish a valid source creation by a fake one?

**Comment by blootsvoets** [comment]
1. an attacker would have
  a. valid user ID credentials
  b. the user has to be assigned to a project which has devices assigned to it with dynamic devices or a device where a researcher did not care to fill in the `sourceId` himself
2. an attacker can then register at most one source ID

On the other hand, if researchers manually filled in every source ID, an attacker with valid user credentials can still query those source IDs and upload fake data for them. To me, the risk is quite small, and the convenience is large.

**Comment by fnobilia** [comment]
> the user has to be assigned to a project which has a dynamic device assigned to it or a device where a researcher did not care to fill in the sourceId or expectedSourceId himself

Ok, the fact that a clinician has to create a `dynamic` device for the subject was not clear. Ok it looks ok to me.

What about the device reusability? A subject can reuse a device previously used by another subject, do we persist and share `sourceId` across projects?

**Comment by blootsvoets** [comment]
I'd suggest that a device can be shared between projects, but the data model is currently not structured like that.

**Comment by nivemaham** [comment]
@blootsvoets @fnobilia I am not very clear about the distinction between `sourceId` and `expectedSourceId`. 1. Why do we have both? 
2. Do we persist both of them or one or the other could be derived programmatically? 
Further,  I would like to clearly know the definition and the constraints of `sourceName` and `sourceId` so that the data model could be implemented accordingly. IMO, i thought the `sourceId` would be `A00017` for `Empatica E4` and `generated id` for `AndroidPhone` since it is unique for a device. 
Currently, the design expects the `sourceId` not to be `null-able` and `unique`. If we want to have both `sourceName` and `sourceId`, i would like to know how we envision the validation of both fields.

**Comment by blootsvoets** [comment]
Ok the constraints as I saw them:

- `expectedSourceId` (typically entered by a researcher/clinician)  is a substring of `sourceId`
- `expectedSourceName` (typically entered by a researcher/clinician) is a substring of `sourceName`.
- `sourceId` is unique except when `null`. It is typically a MAC-address or a UUID reported by the device.
- `sourceName` is the name returned by a device or `null`

**Comment by fnobilia** [comment]
It's not clear to me what is a `expectedSourceName` and `sourceName`.

**Comment by fnobilia** [comment]
```
HTTP POST /api/user/devices
{
  "devices": [
    {
      "id": "some-uuid",
      "name": "Empatica E4 - A00017",
      "sourceId": "AB:01:CD:23:EF:45",
      "firmware": "E4-2.1.0",
      "model": "E4.A",
      "os": null
    }
  ]
}
```

According to the above example, @blootsvoets @nivemaham  I do understand `expectedSourceName`, but I do not understand the `expectedSourceId` field. Could you clarify?

**Comment by blootsvoets** [comment]
No, you're right. I suppose for now `expectedSourceName` would probably be sufficient.
