### ISSUE TITLE
JWT does not contain sub claim

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-CNS/ManagementPortal#41]
One of the standard fields in a JWT is `sub` (subject), which is the global ID of the user in the system, but Spring apparently does not generate it. It does generate `user_name`, but that is not a standard. Proposal: the `sub` field should match the `userId` field that the Kafka streams use. In the case that people are using the ManagementPortal for user and ID management, that would be the user ID, if an external user management system is used and that system exposes the `userId` that researchers want to use, could `sub` be set to be the `externalId`?

**Comment by blootsvoets** [comment]
According to the [JWT spec](https://self-issued.info/docs/draft-ietf-oauth-json-web-token.html#rfc.section.4.1.2):

> The sub (subject) claim identifies the principal that is the subject of the JWT. The claims in a JWT are normally statements about the subject. The subject value MUST either be scoped to be locally unique in the context of the issuer or be globally unique. The processing of this claim is generally application specific. The sub value is a case-sensitive string containing a StringOrURI value. Use of this claim is OPTIONAL.

**Comment by dennyverbeeck** [comment]
#42 adds `sub`, `iat` and `iss` claims to the JWT, as well as a `roles` claim. The decoded payload now looks like this:
```JSON
{
  "sub": "admin",
  "aud": [
    "res_ManagementPortal"
  ],
  "sources": [],
  "user_name": "admin",
  "scope": [
    "read",
    "write"
  ],
  "roles": [
    ":ROLE_SYS_ADMIN",
    ":ROLE_USER",
    "TestProject:ROLE_PROJECT_ADMIN"
  ],
  "iss": "ManagementPortal",
  "exp": 1498128986,
  "iat": 1498127186,
  "authorities": [
    "ROLE_SYS_ADMIN",
    "ROLE_USER"
  ],
  "jti": "1f1aabae-f4c9-4faa-a0bb-05c33a220f63",
  "client_id": "ManagementPortalapp"
}
```
@blootsvoets, @nivemaham, i think we should leave the 'system roles', i.e. the roles without associated project, out of the `roles` claim. An application like Rest-API does not need to know the ManagementPortal roles of the user, only the project roles. What do you think? If you agree i'll do one more commit to #42, and merge it to dev.

**Comment by dennyverbeeck** [comment]
Merged to dev, closing this since sub claim is now present in the JWT.
