### ISSUE TITLE
Logging operation

### ISSUE THREAD

**Issue by fnobilia** [RADAR-CNS/ManagementPortal#44]
We should audit/log all operations that a Management Portal user does. In this way there is a clear understanding of `who did what and when`.

**Comment by dennyverbeeck** [comment]
#133 implements auditing through a JPA Event Listener. I think we can use the same approach, i.e. use the spring application event framework with event listeners, to log important events in production mode in a unified way. For logging debug messages using a `Logger` in each class seem totally fine.
