### ISSUE TITLE
Add SSO login form

### ISSUE THREAD

**Issue by dennyverbeeck** [RADAR-CNS/ManagementPortal#50]
Add single sign on login form, where e.g. dashboard can redirect it's users to to log in to the system.

**Comment by nivemaham** [comment]
@dennyverbeeck Can't we use/reuse part of the implementation of the current login page?

**Comment by dennyverbeeck** [comment]
Good point, i'll use that form as a basis, probably very little needs to be adapted from it

**Comment by dennyverbeeck** [comment]
SSO login form is now ready for testing in the [`add_sso_login_form`](https://github.com/RADAR-CNS/ManagementPortal/tree/add_sso_login_form) branch. The user authorization endpoint is `/oauth/confirm_access` and the token endpoint is `/oauth/token`. You could use e.g. Postman to test (set the authorization type to OAuth2.0), you could use `pRMT` and client id and leave the client secret empty. I have tested with postman, and with a sample Spring MVC app and both worked without issues. I expect that an Angular app will go without problems as well. Does somebody have a sample angular app already to test with @blootsvoets @nivemaham ?

Still needed: some better error handling when someone tries to authenticate with a non-existing oauth client ID.
