### ISSUE TITLE
Human readable identifier

### ISSUE THREAD

**Issue by fnobilia** [RADAR-CNS/ManagementPortal#54]
Alongside with `REDCap` and `RADAR` ids, we can create a simple human readable identifier using the concatenation of
- *RADAR-CNS Work Package* (MDD, MS, EPY)
- *Site* (London, Barcelona, Milan, etc..)
- *REDCap Id*
In the Management Portal, this information will be treated as `metadata`.

The generated value will be unique as long as a site will use a single REDCap instance.

**Comment by nivemaham** [comment]
Closed by [PR61](https://github.com/RADAR-CNS/ManagementPortal/commit/4afb48cfeb8c057dfaec49125b17ddfa366773ba)
