### ISSUE TITLE
Subject enrollment enhancements

### ISSUE THREAD

**Issue by dennyverbeeck** [RADAR-CNS/ManagementPortal#77]
Some suggested enhancements for subject enrollment:

- [x] The user related to a subject should be activated by default on creation
- [x] Remove the email field from subject creation dialog
- [x] Create a scheduled method to look for users related to a subject, that have not yet logged in after some amount of time. Still need to decide what action to perform: set a metadata tag, send an email alert to the project admin, ...

**Comment by dennyverbeeck** [comment]
First two points are resolved with #79

**Comment by nivemaham** [comment]
Issue is currently closed with default user activation and removing email sending feature. The scheduled task ot monitor active users can be done later.
