### ISSUE TITLE
Remove tokens-related to a subject when a subject is discontinued/removed

### ISSUE THREAD

**Issue by nivemaham** [RADAR-CNS/ManagementPortal#80]
We need to revoke the access-token and refresh token related to a subject when a subject is removed or discontinued

**Comment by dennyverbeeck** [comment]
Making the associated `User` deactivated will prevent a refresh token from being used to issue a new access token. We should modify `SubjectService.discontinueSubject` to do this. The `SubjectStatus.DISCONTINUED` should probably be modified to indicate that `activated=false` and `removed=true`.

Access tokens can't be revoked once they are issued. It's the nature of not having a central token store with JWT. However even in setups where you do have a central token store, usually a secured resource will not call the token introspection endpoint with every request, but cache the result for a small period of time. So functionally having a JWT with 30 minute validity is the same as having a token store where a secured resource caches the token introspection result for 30 minutes.
