### ISSUE TITLE
Investigate on how to securly configue oauth client credentials for production evnviorment

### ISSUE THREAD

**Issue by nivemaham** [RADAR-CNS/ManagementPortal#82]
Currently we are loading `oauth-client credentials` from csv. The test credentials used for dev/testing are publicly available. We need to find a way to securely handle this for production environment. Maybe mounting csv file as volume would help in docker compose? and add some environment variables to load values for MP front-end.
Any suggestions are welcome. @dennyverbeeck

**Comment by nivemaham** [comment]
Cannot find a proper solution yet. Given the time-line, i propose to build MP from source on production and change credentials before building. Few other changes of MP on production are also currently inevitable for a secured deployment based on current deployment strategy.

**Comment by dennyverbeeck** [comment]
I agree with the comments in the PR you linked to. For now we keep it in the CSV file, and we'll look into dynamic registration (#18) as soon as possible.
